import { ExperienceItem } from '@/types/type';

export const experienceDatas: ExperienceItem[] = [
    {
        id: 1,
        name: `${import.meta.env.VITE_PC}`,
        url: `https://${import.meta.env.VITE_PC_S}.kr`,
        component: `/project/1`,
        desc: 'AI 사진 변환 기능을 가진 광고 수익 모델 사이트의 사용자 페이지와 관리자 페이지 프론트 1인 개발',
        team: ['자사 프론트엔드 개발자 1명, 백엔드 개발자 1명'],
        period: '2023.11 ~ 2023.12',
        stack: 'vite, vue3, typescript, pinia, axios, scss',
        function: [
            '변환 전, 후 사진 비교 기능 구현',
            '리뷰 등록 및 등록된 리뷰 자동 상하 롤링 시스템 구현',
            '파일 다운로드 기능 구현',
            '로그인, 로그아웃 구현',
            '광고 등록, 조회, 수정, 페이지네이션 기능 구현',
            '데이터의 차트화',
            '엑셀파일 다운로드 기능 구현',
        ],
    },
    {
        id: 2,
        name: import.meta.env.VITE_TOON,
        url: `https://beta.${import.meta.env.VITE_TOON_S}.com`,
        component: `/project/2`,
        desc: `웹툰 자동 번역 툴과 클라이언트,번역가를 매칭해주는 기능의 자체 플랫폼 구축`,
        team: ['자사 프론트엔드 개발자 2명, 백엔드 개발자 1명'],
        period: '2023.03 ~ 2022.11',
        stack: 'Nuxt3, typescript, pinia, nuxtauth, scss',
        function: [
            '회원 가입, 로그인, 마이페이지 등 회원 정보 관련 기능 프론트 개발',
            '클라이언트와 번역가 매칭 기능',
            '프로젝트의 검색, 정렬 기능 구현',
            '알림 기능 구현',
        ],
    },
    {
        id: 3,
        name: '자사 기술 소개 사이트',
        url: `https://tech.${import.meta.env.VITE_IDEA}.com`,
        component: '/project/3',
        desc: '자사 기술 소개 페이지 프론트 개발',
        team: ['1인 개발'],
        period: '2023.05',
        stack: 'vue3, swiper, scss',
        function: ['vanilla javascript로 페이지 슬라이드 구현'],
    },
    {
        id: 4,
        name: '자사 홈페이지',
        url: `https://${import.meta.env.VITE_IDEA}.com`,
        component: '/project/acon',
        desc: '자사 대표 홈페이지와 관리자 페이지 프론트 개발',
        team: ['자사 프론트엔드 개발자 2명, 백엔드 개발자 1명'],
        period: '2022.11 ~ 2023.01',
        stack: 'vue3, pinia, axios, scss, swiper, i18n',
        function: [
            'Vanilla Javascript로 개발된 기존 대표 홈페이지를 Vue3로 마이그레이션',
            '스크롤 애니메이션 구현',
            '반응형 웹 개발',
            'i18n을 이용한 다국어 기능 구현',
            '관리자 페이지 기능 전체 개발',
        ],
    },
];

export const sideProjectDatas: ExperienceItem[] = [
    {
        id: 5,
        name: '포트폴리오 사이트',
        url: 'https://github.com/pparksso/portfolio__react',
        component: `/project/5`,
        desc: '개인 포트폴리오 사이트',
        team: ['1인 개발'],
        period: '2023.12',
        stack: 'React, vite, typescript, tailwindcss',
        function: [
            'UX/UI 디자인 제작 및 반응형 레이아웃 구현',
            '공통 컴포넌트화',
            '메일 전송 기능 구현',
        ],
    },
    {
        id: 6,
        name: `여행 블로그`,
        url: `https://github.com/pparksso/travelNote`,
        component: `/project/7`,
        desc: '여행의 순간을 기록하고, 소통할 수 있는 사이트',
        team: ['1인 개발'],
        period: '2022.08.28 ~ 2022.09.24',
        stack: 'javascript, nodejs, express, mongodb(mongoose), heroku',
        function: [
            'UX/UI 디자인 제작 및 반응형 레이아웃 구현',
            '로그인, 로그아웃, 마이페이지 수정, 회원 탈퇴 등 회원 관련 기능 구현',
            '글 작성, 수정, 삭제 조회 기능 구현',
            '하트 누르기, 댓글 기능',
            '본인 게시물, 하트 누른 게시물 등 필터 기능',
        ],
    },
];
